name: Google Cloud SQL Proxy Action
description: run the Google Cloud SQL Proxy in a GitHub Action's context

branding:
  icon: database
  color: blue

inputs:
  token:
    description: Service Account OIDC token
    required: true

  connection:
    description: CloudSQL connection name
    required: true

  port:
    description: Listening port
    required: true

  version:
    description: CloudSQL Proxy Version
    required: false
    default: 1.22.0-alpine

  sleep:
    description: time between connection checks
    required: false
    default: 3

  attempts:
    description: number of total connection checks
    required: false
    default: 10

runs:
  using: composite
  steps:
    - name: "sql-proxy: start container"
      run: ${{ github.action_path }}/scripts/proxy.sh ${{ inputs.version }} ${{ inputs.port }} ${{ inputs.connection }} ${{ inputs.token }}
      shell: bash

    - name: "sql-proxy: wait for connection"
      run: ${{ github.action_path }}/scripts/wait.sh ${{ inputs.port }} ${{ inputs.sleep }} ${{ inputs.attempts }}
      shell: bash
